/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui;

import java.sql.Date;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.poi.sl.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.lang.*;


import dao.ChiTietHoaDonDAO;
import dao.HoaDonDAO;
import entity.ChiTietHoaDon;
import entity.HoaDon;

/**
 *
 * @author Admin
 */
public class QuanLyHoaDon extends javax.swing.JPanel {
	private HoaDonDAO hoaDon_DAO = new HoaDonDAO();
    private ChiTietHoaDonDAO cthd_DAO = new ChiTietHoaDonDAO();
    DefaultTableModel dtm = null;
    
    public QuanLyHoaDon() {
        initComponents();
        loadTblHoaDon();
    }
    
    public void clearTableHoaDon() {
        dtm = (DefaultTableModel) jTable_DanhSachHoaDon.getModel();
        dtm.setRowCount(0);
    }
    
  //load table hóa đơn
    public void loadTblHoaDon() {
        clearTableHoaDon();
        hoaDon_DAO = new HoaDonDAO();
        dtm = (DefaultTableModel) jTable_DanhSachHoaDon.getModel();
        ArrayList<HoaDon> listHoaDon = hoaDon_DAO.getAllHoaDon();
        for (HoaDon hoaDon : listHoaDon) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(hoaDon.getNgayLapHD());
            Object[] rowData = {hoaDon.getMaHD(), date, hoaDon.getNhanVien().getTenNhanVien(), hoaDon.getKhachHang().getTenKhachHang(), hoaDon.tongTien()};
            dtm.addRow(rowData);
        }

    }
    
  //clear table sản phẩm
    public void clearTableChiTietHoaDon() {
        dtm = (DefaultTableModel) jTable_DanhSachSanPham.getModel();
        dtm.setRowCount(0);
    }

    //load table sản phẩm
    public void loadTblChiTietHoaDon(String id) {
        clearTableChiTietHoaDon();
        dtm = (DefaultTableModel) jTable_DanhSachSanPham.getModel();
        ArrayList<ChiTietHoaDon> listCTHD = getListChiTietHoaDonByHoaDon(id);
        for (ChiTietHoaDon chiTietHoaDon : listCTHD) {
            Object[] rowData = {chiTietHoaDon.getSanPham().getMaSP(),chiTietHoaDon.getSanPham().getTenSP(), chiTietHoaDon.getSanPham().getLoaiSP(), chiTietHoaDon.getSoLuong(), chiTietHoaDon.getSanPham().getDonGiaBan(), chiTietHoaDon.thanhTien()};
            dtm.addRow(rowData);
        }

    }
    
    public ArrayList<ChiTietHoaDon> getListChiTietHoaDonByHoaDon(String id) {
        cthd_DAO = new ChiTietHoaDonDAO();
        return cthd_DAO.getCTHDById(id);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	tbl_HoaDon = new javax.swing.JTable();
        tbl_SanPham = new javax.swing.JTable();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        popupMenu1 = new java.awt.PopupMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnTimKiem = new javax.swing.JButton();
        btnXuatHoaDon = new javax.swing.JButton();
        jPanelTimKiem = new javax.swing.JPanel();
        jButtonALL = new javax.swing.JButton();
        jLabelFrom = new javax.swing.JLabel();
        jDateChooserFrom = new com.toedter.calendar.JDateChooser();
        jLabelTo = new javax.swing.JLabel();
        jDateChooserTo = new com.toedter.calendar.JDateChooser();
        jPanel_DanhSachHoaDon = new javax.swing.JPanel();
        jScrollPane_DanhSachHoaDon = new javax.swing.JScrollPane();
        jTable_DanhSachHoaDon = new javax.swing.JTable();
        jPanel_ChiTietHoaDon = new javax.swing.JPanel();
        jScrollPane_DanhSachSP = new javax.swing.JScrollPane();
        jTable_DanhSachSanPham = new javax.swing.JTable();
        jLabelQuanLyHoaDon = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("jMenu8");

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar5.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar5.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar6.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar6.add(jMenu14);

        popupMenu1.setLabel("popupMenu1");

        jMenuItem2.setText("jMenuItem2");

        setPreferredSize(new java.awt.Dimension(1300, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTimKiem.setBackground(new java.awt.Color(255, 102, 102));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Add-icon.png"))); // NOI18N
        btnTimKiem.setText("TÌM KIẾM");
        btnTimKiem.setBorder(null);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 210, 40));

        btnXuatHoaDon.setBackground(new java.awt.Color(153, 255, 204));
        btnXuatHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_maintenance_30px.png"))); // NOI18N
        btnXuatHoaDon.setText("XUẤT HÓA ĐƠN");
        btnXuatHoaDon.setBorder(null);
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });
        add(btnXuatHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, 210, 40));

        jPanelTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN TÌM KIẾM"));
        jPanelTimKiem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonALL.setText("ALL");
        jButtonALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonALL1ActionPerformed(evt);
            }
        });
        jPanelTimKiem.add(jButtonALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 40));

        jLabelFrom.setText("TỪ NGÀY:");
        jPanelTimKiem.add(jLabelFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, 40));
        jPanelTimKiem.add(jDateChooserFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 260, 40));

        jLabelTo.setText("ĐẾN NGÀY:");
        jPanelTimKiem.add(jLabelTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 70, 40));
        jPanelTimKiem.add(jDateChooserTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 260, 40));

        add(jPanelTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 910, 100));

        jPanel_DanhSachHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN HÓA ĐƠN"));
        jPanel_DanhSachHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_DanhSachHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "MÃ HĐ", "NGÀY LẬP HOÁ ĐƠN", "TÊN NHÂN VIÊN", "TÊN KHÁCH HÀNG", "TỔNG TIỀN"
            }
        ));
        jTable_DanhSachHoaDon.setRowHeight(30);
        /*jTable_DanhSachHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_DanhSachHoaDon
            }
        });*/
        jScrollPane_DanhSachHoaDon.setViewportView(jTable_DanhSachHoaDon);

        jPanel_DanhSachHoaDon.add(jScrollPane_DanhSachHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1230, 190));

        add(jPanel_DanhSachHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1270, 220));

        jPanel_ChiTietHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder("CHI TIẾT HÓA ĐƠN"));
        jPanel_ChiTietHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_DanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "MÃ SP", "TÊN SP", "LOẠI SẢN PHẨM", "SỐ LƯỢNG", "ĐƠN GIÁ", "THÀNH TIỀN"
            }
        ));
        jTable_DanhSachHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
            	jTable_DanhSachHoaDon_HoaDonMousePressed(evt);
            }
        });
        jScrollPane_DanhSachSP.setViewportView(jTable_DanhSachSanPham);
        jTable_DanhSachSanPham.setRowHeight(30);
        jPanel_ChiTietHoaDon.add(jScrollPane_DanhSachSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1230, 210));

        add(jPanel_ChiTietHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1270, 240));

        jLabelQuanLyHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        jLabelQuanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelQuanLyHoaDon.setForeground(new java.awt.Color(255, 51, 0));
        jLabelQuanLyHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuanLyHoaDon.setText("QUẢN LÝ HÓA ĐƠN");
        add(jLabelQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 40));
    }// </editor-fold>//GEN-END:initComponents
    private void jTable_DanhSachHoaDon_HoaDonMousePressed(java.awt.event.MouseEvent evt) {
        int row = jTable_DanhSachHoaDon.getSelectedRow();

        DefaultTableModel dtm = (DefaultTableModel) jTable_DanhSachHoaDon.getModel();
        String id = dtm.getValueAt(row, 0).toString().trim();
    
        loadTblChiTietHoaDon(id);
    }
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    	clearTableHoaDon();
    	clearTableHoaDon();
    	SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    	String from = formatter.format(jDateChooserFrom.getDate());
    	String to = formatter.format(jDateChooserTo.getDate());
    	Date ngayBatDau = Date.valueOf(from);
    	Date ngayKetThuc = Date.valueOf(to);
    	
    	hoaDon_DAO = new HoaDonDAO();
        ArrayList<HoaDon> listHoaDon = hoaDon_DAO.getAllHoaDon();
        DefaultTableModel dtml = (DefaultTableModel) jTable_DanhSachHoaDon.getModel();
        for(HoaDon hoaDon : listHoaDon){
            if((hoaDon.getNgayLapHD().before(ngayKetThuc) && hoaDon.getNgayLapHD().after(ngayBatDau)) || hoaDon.getNgayLapHD().equals(ngayBatDau) || hoaDon.getNgayLapHD().equals(ngayKetThuc)) {

            Object[] rowdata={hoaDon.getMaHD(),hoaDon.getNgayLapHD(), hoaDon.getNhanVien().getTenNhanVien(), 
                hoaDon.getKhachHang().getTenKhachHang()};
            dtml.addRow(rowdata);

            }
        }
    }//GEN-LAST:event_btn3ActionPerformed
    private static String[] Columns = {"MÃ HĐ", "NGÀY LẬP HĐ", "TÊN NHÂN VIÊN", "TÊN KHÁCH HÀNG", "TỔNG TIỀN"};
    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
    	// Chọn vị trí file
        XSSFWorkbook excelJTableExport = new XSSFWorkbook();
        XSSFSheet excelSheet = excelJTableExport.createSheet("Danh sách hoá đơn");
        BufferedOutputStream excelBos = null;
        try {
 
            //Chọn nơi lưu
            JFileChooser excelFileChooser = new JFileChooser();
            //Tiêu đề ô save
            excelFileChooser.setDialogTitle("Save As ..");
            //Định dạng chỉ xls, xlsx, xlsm files
            FileNameExtensionFilter fnef = new FileNameExtensionFilter("Files", "xls", "xlsx", "xlsm");
            excelFileChooser.setFileFilter(fnef);
            int chooser = excelFileChooser.showSaveDialog(null);
            XSSFCell excelCell = null;
            //Kiểm tra nút save nhấn chưa
            if (chooser == JFileChooser.APPROVE_OPTION) {
                //Nếu click thì đẩy dữ liệ
            	//Tạo tiêu đề
            	XSSFRow excelRow = excelSheet.createRow(0);
            	for (int j = 0; j < jTable_DanhSachHoaDon.getColumnCount(); j++) {
                    excelCell = excelRow.createCell(j);
                    excelCell.setCellValue(Columns[j]);
                }
                //Vòng lặp qua cột và hàng của bảng jtable_DanhSachHoaDon để lấy giá trị
                for (int i = 1; i < jTable_DanhSachHoaDon.getRowCount(); i++) {
                    excelRow = excelSheet.createRow(i);
                    for (int j = 0; j < jTable_DanhSachHoaDon.getColumnCount(); j++) {
                        excelCell = excelRow.createCell(j);
                        excelCell.setCellValue(jTable_DanhSachHoaDon.getValueAt(i, j).toString());
                    }
                }
                FileOutputStream excelFos = new FileOutputStream(excelFileChooser.getSelectedFile() + ".xlsx");
                excelBos = new BufferedOutputStream(excelFos);
                excelJTableExport.write(excelBos);
                JOptionPane.showMessageDialog(null, "Xuất thành công");
            }
 
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                if (excelBos != null) {
                    excelBos.close();
                }
                if (excelJTableExport != null) {
                    excelJTableExport.close();
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }

		
    	//GEN-LAST:event_btn8ActionPerformed
    private void jButtonALL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	loadTblHoaDon();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JButton jButtonALL;
    private com.toedter.calendar.JDateChooser jDateChooserFrom;
    private com.toedter.calendar.JDateChooser jDateChooserTo;
    private javax.swing.JLabel jLabelQuanLyHoaDon;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel_DanhSachHoaDon;
    private javax.swing.JPanel jPanelTimKiem;
    private javax.swing.JPanel jPanel_ChiTietHoaDon;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane_DanhSachSP;
    private javax.swing.JScrollPane jScrollPane_DanhSachHoaDon;
    private javax.swing.JTable jTable_DanhSachSanPham;
    private javax.swing.JTable jTable_DanhSachHoaDon;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable tbl_HoaDon;
    private javax.swing.JTable tbl_SanPham;
    // End of variables declaration//GEN-END:variables

}
